export type ModalType =
  | 'profile'
  | 'stream'
  | 'site'
  | 'bookmark'
  | 'chat-widget'
  | 'donation'
  | 'notify-user'
  | 'setting-emoji'
  | 'upload-image-chat'
  | 'add-stream'
  | 'upload-memo'
  | 'test-command'
  | 'chat-reaction'
  | 'donation-send';
